main/urls.py
from django.urls import path
from . import views
from .views import BlogListViews,TagListViews,blog_detail

app_name= "main"

urlpatterns = [
   path('',BlogListViews.as_view(),name='blog-homepage'),
   path('about/',views.about,name='blog-about'),
   #path('blog/<int:pk>/',BlogDetailViews.as_view(),name='blog_detail'),
   #path of class based view is removed from the url patterns, also detailview.html page is reshaped into detail.html file.
   path('blog/tagged/<slug:slug>/',TagListViews.as_view(),name='tagged_blogs'),
   path('blog/tagged/book/',TagListViews.as_view(),name='book_blog'),
   path('blog/<int:id>/',blog_detail,name='blog_page'),
   path('blog/latestprojects/',views.latestproj,name='latest_proj'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("",include("main.urls")),
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=400,verbose_name='Blog Title')
    content=RichTextUploadingField(verbose_name='Blog Content')
    date_posted=models.DateTimeField(default=timezone.now,verbose_name='Published Date')
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    tags=TaggableManager(verbose_name='tags',help_text='Use comma seperated names for separate tags')
   
    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from django.views.generic import ListView,DetailView
from .models import Blog
from taggit.models import Tag
from django.shortcuts import get_object_or_404
from django.db.models import Count

#creating views using class based views

class BlogListViews(ListView):
    model=Blog
    template_name='main/home.html' #class based view require template as well <app name>/<model name>_<viewtype>.html
    ordering=['-date_posted'] # We have made a slight change in the template also, where the for loop as been changed (ref: object list)
#CBV is removed from the code    
#class BlogDetailViews(DetailView):
    #model=Blog
    #template_name='main/detailview.html'

class TagListViews(ListView):
    """This is used for having a list view for tags that we have added using taggit in models"""
    model=Blog
    template_name='main/home.html'

    def get_queryset(self):
        return Blog.objects.filter(tags__slug=self.kwargs.get("slug")).all()
    class meta:
        ordering = ['-date_posted']
    def get_context_data(self, **kwargs):
        context=super(TagListViews,self).get_context_data(**kwargs)
        context["tag"]=self.kwargs.get("slug")
        return context
    
    
#defining about page 
def about(request):
    return render(request,'main/about.html',{'title':'About'})

#blog detail page is remade. Earlier CBV were being used and now function based views is used to sort out the problem with similar pages
def blog_detail(request,id):
    blog=get_object_or_404(Blog,id=id)
    tags = blog.tags.all()
    similar_blog = Blog.objects.filter(tags__in=tags).exclude(id=blog.id)
    return render(request, 'main/detail.html', {'blog': blog, 'similar_blog': similar_blog})

#defining latest project page
def latestproj(request):
    return render(request,'main/latestprojects.html',{'title':latestproj})

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
    <h1> Blog About!</h1>
{% endblock content %}

main/templates/main/base.html
<!-- The base template is used as a base to encapsulate all the common elements of different templates. The method used here is template inheritance-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- share this code block for social media sharing-->
    <script type='text/javascript'
        src='https://platform-api.sharethis.com/js/sharethis.js#property=5e1d66b09913370013b30809&product=inline-share-buttons&cms=website'
        async='async'></script>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
        <title>KaushalBundel Blog - {{title}}</title>
    {% else %}
        <title>KaushalBundel Blog</title>
    {% endif %} 
</head>
<!-- This code base is for the nav bar-->
<body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top"> <!-- using this line, nav bar properties have been changed-->
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'main:blog-homepage' %}">KaushalBundel</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'main:book_blog'  %}">Books</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

    <!-- this is the code base for content that we are fetching from db-->
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Check this out !!</h3>
                    <p class='text-muted'>
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light"><a href="{% url 'main:book_blog' %}">Books</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{% url 'main:blog-about' %}">About Me</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{% url 'main:latest_proj' %}">Current Projects</a></li>
                            <li class="list-group-item list-group-item-light">Connect with me</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    </body>
</body>

</html>

main/templates/main/detail.html
{% extends "main/base.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2"></a>{{ blog.author }}</a>
            <small class="text-muted">{{ blog.date_posted|date:"jS M Y" }}</small>
        </div>
        <h2 class="article-title">{{ blog.title }}</h2>
        <p class="tags">Tags:
            {% for tag in blog.tags.all %}
            <a href="{% url "main:tagged_blogs" tag.slug %}">#{{tag}}</a>
            {% endfor %}
        </p>
        <div class="sharethis-inline-share-buttons"></div>
        <div>
            <p class="article-content">{{ blog.content |safe}}</p>
        </div>
        <h2 class="article-title">Recommended Posts</h2>
        <ul>
            {% for blog in similar_blog %}
            <li>
                <a href="{% url "main:blog_page" blog.id %}">{{blog.title}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</article>
{% endblock content %}

main/templates/main/detailview.html
{% extends "main/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2"></a>{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"jS M Y" }}</small>
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="tags">Tags:
                {% for tag in blog.tags.all %}
                <a href="{% url "main:tagged_blogs" tag.slug %}">#{{tag}}</a>
                {% endfor %}
            </p>
            <p class="article-content">{{ object.content }}</p>
            <h2 class="article-title">Recommended Posts</h2>
            <ul>
                {% for blog in similar_blog %}
                <li>
                    <a href="{% url "main:blog_detail" blog.id %}">{{blog.title}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </article>
{% endblock content %}

main/templates/main/home.html
{% extends "main/base.html" %}
{% block content %}
    {% for post in object_list %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"jS M Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'main:blog_page' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content|truncatechars:400 |safe }}</p>
                <a class="mr-2" href="{% url 'main:blog_page' post.id %}">Read More</a>
                <p class="tags">Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url "main:tagged_blogs" tag.slug %}">#{{tag}}</a>
                    {% endfor %}
                <div class="sharethis-inline-share-buttons"></div>
                </p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

main/templates/main/latestprojects.html
{% extends "main/base.html" %}
{% block content %}
<h1> Latest Projects</h1>
{% endblock content %}